/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.demo.base.api;

import com.example.demo.base.model.Order;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-01-11T23:42:49.995+05:30[Asia/Calcutta]")
@Api(value = "getOrder", description = "the getOrder API")
public interface GetOrderApi {

    Logger log = LoggerFactory.getLogger(GetOrderApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "get customer By orderId", nickname = "getOrderOrderIdGet", notes = "you can delete customer by orderId ", response = Order.class, tags={ "orders", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = Order.class) })
    @RequestMapping(value = "/getOrder/{orderId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Order> getOrderOrderIdGet(@ApiParam(value = "",required=true) @PathVariable("orderId") Integer orderId
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\r\n  \"orderId\" : 0,\r\n  \"customerId\" : {\r\n    \"debitAvailable\" : 1.4658129805029452,\r\n    \"customerAddress\" : \"customerAddress\",\r\n    \"modeOfPayment\" : \"modeOfPayment\",\r\n    \"customerId\" : 6,\r\n    \"customerName\" : \"customerName\",\r\n    \"status\" : \"active\"\r\n  },\r\n  \"orderStatus\" : \"orderStatus\",\r\n  \"orderProductId\" : [ {\r\n    \"productId\" : 5,\r\n    \"company\" : \"company\",\r\n    \"inventory\" : 2,\r\n    \"productName\" : \"Widget Adapter\",\r\n    \"productPrice\" : 5.637376656633329\r\n  }, {\r\n    \"productId\" : 5,\r\n    \"company\" : \"company\",\r\n    \"inventory\" : 2,\r\n    \"productName\" : \"Widget Adapter\",\r\n    \"productPrice\" : 5.637376656633329\r\n  } ],\r\n  \"orderValue\" : 7.061401241503109\r\n}", Order.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default GetOrderApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
