apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30001